### ISSUE TITLE
Nothing happens when I run the program

### ISSUE THREAD

**Issue by Xebtria** [GalaxyEham/FrostyToolSuite#10]
The exe shows up in task manager for a second or so, then disappears again, and nothing happens.

using 1.0.2b of FMM
1.0.9 of me:a
win10 pro build 1703

**Comment by GalaxyEham** [comment]
There are three things to try:

1. Delete the ModData directory completely from your Mass Effect install directory then try running via the mod manager again.
2. Untick read only on the Mass Effect install directory and apply to all subdirectories and files, and try running the mod manager again.
3. Lastly, reinstall mass effect, since its possible that the permissions to the folder have gone all strange.

**Comment by Xebtria** [comment]
Hi

1. I don't even have a moddata directory.
2. I did that, but nothing changed
3. I did not do that because I do not have the time at the moment to do that, as I only have very little PC time anyways, so I want to use the time playing the game, not waiting to download (again). I might try it at some time in the future, if no other solution comes up, but not right now.

anyways, to be frank, I actually did not expect any of these suggestions to fix anything, as I never have told the mod manager where my exe is located, so it never could have known anything about the game in the first place, so what would changing anything with the read only etc solve?

also, I additionally checked by disabling my firewall etc, I thought maybe it interferes, but no, did not help either.

**Comment by GalaxyEham** [comment]
Oh so u mean the Mod Manager is not launching? u need to be more clear, as there is another issue involving the game not launching. Do you have rivatuner installer?

**Comment by Xebtria** [comment]
Yes, the Mod Manager is not launching, sorry for not being clear.

I don't recall having rivatuner installed, but there is a "rivatunerstatisticsserver v6.5.0.8709" in my systray... so I guess it is installed?

**Comment by GalaxyEham** [comment]
disable it, thats whats stopping the mod manager from working.

**Comment by Xebtria** [comment]
ok it worked after I got this rivatuner thing uninstalled, which was more difficult than I'd like to admit.

however, when I pressed the launch button, it then said something like moddata does not exist and requires admin privileges to create and If I want to do that yada yada, I clicked yes and then the windows UAC message came up and literally killed my headphones. what the actual F happened there? it was so loud and then I only had a permanent beep on the phones. Luckily I had some replacement phones (which work, so yeah, my $300 phones are now dead :( ).... 

and the UAC message cannot be the problem either, because I have a batch file running each time I start the PC, and this was normal volume.

**Comment by GalaxyEham** [comment]
It aint my tool that did that, it displays the standard UAC window, and which in turn would play the standard windows sounds, i dont customize anything like that. But since ur original issue is solved, im gonna go ahead and close this issue now
