### ISSUE TITLE
CLI Command Line Interface

### ISSUE THREAD

**Issue by acoppola** [GalaxyEham/FrostyToolSuite#100]
Hi GalaxyEham, do you think this is possible to import or replace dds graphics with cli? or at least generate a project file?

I know it is to much for a Change Request, but it will be useful to import and replace many files at once.

Thanks

**Comment by GalaxyEham** [comment]
no, and there is no plans for implementing this in the future, the idea behind the editor is not for mass import/export of objects, but to become an all in one environment for creating and editing mods for Frostbite games, im sure eventually the tool will have the ability to import various assets in one go (via drag n drop) but it is not priority.
