### ISSUE TITLE
FIFA 18 FMM issue

### ISSUE THREAD

**Issue by blafasdkja** [GalaxyEham/FrostyToolSuite#103]
Note: I run it as Admin

One ore more symbolic links could not be created, please restart tool as Administrator.

   en Frosty.ModSupport.FrostyModExecutor.‎‍⁮‬⁫‫⁮‪‏⁯⁯‭‫‍⁮‬‪⁫‬⁬‍‬‭⁫‎‪‌⁭‬‪‍‫⁭‏‏‬‌⁫‏‪‮.⁭‬⁬⁫⁮‭‮⁭‪‭⁪‍‏⁭‏​⁯‏‮‍‏⁯‭‮‫⁭⁪‏⁭‍‬⁫⁫⁫⁫‍‎‮‏‌‮()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Frosty.ModSupport.FrostyModExecutor.guuq>s{PD?Qb\,#1lN{vS7Pqa.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en FrostyEditor.MainWindow.<launchButton_Click>d__18.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
please restart tool as Administrator is just a suggestion, it may not ultimately be the fix, however ur issue is u do not have the permissions (even as admin) to create the symbolic links required for modding, you need to resolve this before going any further
