### ISSUE TITLE
Support for FIFA 17

### ISSUE THREAD

**Issue by qhash1** [GalaxyEham/FrostyToolSuite#11]
Hey,

is it possible to add support for FIFA 17? 
The game had a huge modding community until EA decided to kill it by using Frostbite. 
There are already tools to find and export the files out of the game but so far nobody could inject them into the game again.

I tried to take a stab at it but since the gameprofiles.cfg seems to be encrypted and I can't find the source code I wondered if maybe you could take a look at it.

If you don't have the game, I would be inclined to buy and send you a key since I desperately want to mod this game.

**Comment by GalaxyEham** [comment]
I am happy to give it a go, and have been waiting for someone to reach out from the community to ask, turns out I actually dont need anyone to purchase the game for me, the standard edition is available thru Origin access. Ive added it to my library, but need to check wether or not I have the download limit this month to actually download it (yes Im from a place that still has limits :P).

Is there a discord channel for Fifa17 modding? or potential modding?

**Comment by qhash1** [comment]
Hey, that's awesome!
I don't know any discord channel but there are two major forums online.
One would be soccergaming.com and the other is the moddingway.com Forum - maybe you could reach out to Ariel at Moddingway, he is making the biggest Mod there is for FIFA so he probably could tell you a lot. 

If you want, you can add me on discord.
bcompiler#9984

**Comment by smacx15** [comment]
Hey guys sorry to jump in on this but just wanted to just say for the issue of importing mods to fifa 17 they have been able to import textures but seem to have issue with it. To my understanding of what I had read it seems to be texture issue when using  mea explorer tool and I think they are completely at a stand still with this. These images show what the current issue is.
![5qmjmd](https://user-images.githubusercontent.com/30635007/28841558-96f69486-76f2-11e7-963b-a21e1ce80ba3.jpg)
![dgk9k7](https://user-images.githubusercontent.com/30635007/28841568-9c5934b0-76f2-11e7-9b63-c34befd5bea2.jpg)

**Comment by qhash1** [comment]
He also opened a thread on Moddingway so I think this issue can be closed now. Thank you!
Link to thread: http://www.moddingway.com/forums/thread-30176.html
