### ISSUE TITLE
Fifa 18 - Black screen

### ISSUE THREAD

**Issue by zalook** [GalaxyEham/FrostyToolSuite#113]
I am trying to apply a mod for fifa 18 via Frosty Mod Manger  but when i launch the game , the game starts but with a black screen !

**Comment by Kambyo** [comment]
I don't have any mod and FrostyModManager_v1.0.3.1 can launch my fifa 18 but FrostyModManager_v1.0.4.2 can't. Neither of them can launch the game with mods and it shows no error. Help please?

**Comment by imparsa14** [comment]
> I am trying to apply a mod for fifa 18 via Frosty Mod Manger but when i launch the game , the game starts but with a black screen !

Do you fix them??
My problem same you.
