### ISSUE TITLE
An unhandled exception has occured

### ISSUE THREAD

**Issue by karans025** [GalaxyEham/FrostyToolSuite#119]
Value cannot be null.
Parameter name: value

   at System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
   at FrostySdk.FileSystem.‫‭‌‭‫‬⁪‏‭‎⁮⁯‪‎‎‫⁪‏‫⁭⁭‍‍⁯‍⁬‫‫‌‬⁪‍‏⁮⁫​‏⁮‌⁫‮(Byte[] )
   at FrostySdk.FileSystem.Initialize(Byte[] key)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Era0303** [comment]
Help me

**Comment by Era0303** [comment]
Запрошенная операция требует повышения

в System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) 
в Frosty.ModSupport.FrostyModExecutor. ⁭⁭Ъ⁭Ъ⁮ ⁮ ⁭⁮Ъ⁭⁭⁫⁯ ⁬ ⁫ ⁯⁭⁮⁯Ъ⁫‏Ъ‌ Ъ(String , String , Boolean , Boolean ) 
в Frosty.ModSupport.FrostyModExecutor.⁯​‍⁭Ъ ⁪Ъ ⁯⁪⁯⁮ Ъ⁬Ъ‏ ⁯​ ⁪​‍ЪЪ‍⁮⁭ ⁭​⁭ ⁫⁫⁮‏Ъ. ‍⁫⁪ ⁪⁬ ‏​ ⁬⁭⁭‌⁯⁭⁮⁭‌ ‏⁫‍⁪⁭⁫‌ ⁬‏​Ъ⁫⁬‌Ъ() 
в System.Threading.Tasks.Task.Execute() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в Frosty.ModSupport.FrostyModExecutor.PL/4V#5m#OJ3zFX4X.. z}(.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
в FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext() 
-— Конец трассировка стека из предыдущего расположения, где возникло исключение —- 
в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) 
в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by DartSnack** [comment]
I don't know if I will help you or not because I'm not a geniuse but problem disappeared but other appeared. I just put the file that asks in title of crash (I took it from folder "ThirdParty") and put it on the path that is specified in title of crash. I dunno how it works because I absolutely do not understand anything in this topic! But it gave some result so I don’t even know what to think about it.
