### ISSUE TITLE
Change textures

### ISSUE THREAD

**Issue by AlexRToledo** [GalaxyEham/FrostyToolSuite#12]
Hi @GalaxyEham, I test your tool with DAI (Dragon Age Inquisition) and open it fine. So, you know if I can change companions textures. Example: Change Cassandra for Morrigan head? Thanx, and regards

**Comment by GalaxyEham** [comment]
DAI support is extraction only at this time, I will be working on the modding abilities for DAI in v1.0.4

**Comment by GalaxyEham** [comment]
DAI Support has been added in v1.0.3alpha.
