### ISSUE TITLE
Frosty won't start FIFA 18 been trying to get this to work for hours :(

### ISSUE THREAD

**Issue by Tomlilz** [GalaxyEham/FrostyToolSuite#129]
I've tried getting this to work for a good few hours now, It runs the game then a FIFAConfig.exe protocol type window shows up for around a second, then the play button on Origin blinks a couple times from orange to grey. I've tried multiple versions of Frosty including the new 1.0.4.3. It is not a mod causing this as I cannot launch the game through Frosty without any mods. Please help :(

**Comment by GalaxyEham** [comment]
its permissions, go to the discord server in the link on the wiki and go to the #solutions channel and read thru it, this problem has been mentioned numerous times, and I do not feel like repeating myself yet again
