### ISSUE TITLE
Win 10 1809 Update and Frosty Mod Manager

### ISSUE THREAD

**Issue by Rcj230** [GalaxyEham/FrostyToolSuite#132]
Hello,
           First, thanks for such awesome tools!
Yesterday I was playing Mass Effect Andromeda, then the Windows 10 1809 update rolled in.
Today, I can no longer launch through FMM 1.0.4.4, mods active or no. Andromeda runs from the executable.
Have tried all the possible fixes to no avail.
Just wondering if the bcrypt.dll or the like may no longer be working?

**Comment by cdennis** [comment]
I too have this problem. I noticed a stacktrace in a new window pops up the very first time after deleting ModData.

**Comment by Rcj230** [comment]
> I too have this problem. I noticed a stacktrace in a new window pops up the very first time after deleting ModData.

I did not get a debug window or anything when switching dll's or removing ModData. Odd.
Did have any programs opened when that happened?

**Comment by cdennis** [comment]
On discord, GalaxyMan2015 mentioned thats not a stacktrace, thats the dos command creating symlinks

**Comment by sbradabang** [comment]
I can't launch any game from FMM 1.0.4.4, not only MEA. I think Windows 10 1809 broke too many things, and I'll revert to 1803 with all its bugs.

**Comment by GalaxyEham** [comment]
Aware and resolved, fix will be in 1.0.4.5

**Comment by Rcj230** [comment]
> Aware and resolved, fix will be in 1.0.4.5

@GalaxyEham; Thanks for the update, already rolled back to 1803.
FMM is not alone, 1809 also broke the Script Extender for Skyrim, FO4, Etc.

**Comment by liamcos** [comment]
> > Aware and resolved, fix will be in 1.0.4.5
> 
> @GalaxyEham; Thanks for the update, already rolled back to 1803.
> FMM is not alone, 1809 also broke the Script Extender for Skyrim, FO4, Etc.

So, rolling back to 1803 works ?

**Comment by Rcj230** [comment]
> > > Aware and resolved, fix will be in 1.0.4.5
> > 
> > 
> > @GalaxyEham; Thanks for the update, already rolled back to 1803.
> > FMM is not alone, 1809 also broke the Script Extender for Skyrim, FO4, Etc.
> 
> So, rolling back to 1803 works ?

Worked fine for me and took a lot less time to go back than install. Also fixed the Script Extender issue I was having. If you can make a backup first I would do it. To be on the safe side.
Rolling back a version can sometimes be an adventure.

**Comment by kidstronger** [comment]
> 
> 
> Aware and resolved, fix will be in 1.0.4.5

i'm waiting

**Comment by SpaghettiViking** [comment]
> 
> 
> Aware and resolved, fix will be in 1.0.4.5

Thanks so much! I was beating my head against a wall trying to figure out what I did wrong. Turns out it was Windows 1809 the whole time. >_<

**Comment by Rcj230** [comment]
> hopeless

Don't know about you, but the latest windows update worked for me(Done today). FMM launched ME Andromeda with no issues. Only Frostbite game I have, so can't test further.

**Comment by sbradabang** [comment]
> 
> 
> > hopeless
> 
> Don't know about you, but the latest windows update worked for me(Done today). FMM launched ME Andromeda with no issues. Only Frostbite game I have, so can't test further.

Too many people have this issue, and GalaxyMan is aware of it. I can't launch MEA from FMM in 1809; it opens the process, I find it in task manager consuming CPU and RAM, and that's all: the game never opens its window. I think you have 1803, not 1809.

**Comment by Slayer5934** [comment]
I know I'm not paying for his service but I think all of us would appreciate a status update if possible.. Waiting for M$'s move is a good explanation though..

**Comment by sbradabang** [comment]
> Hate typing, I should have expanded on this. like my prior thread said, I rolled back to 1803. The 1809 is still being processed by MS, but you can still update windows at this point. For those whom wish to wait till all the FMM issues are dealt with should be patient if they do not roll back. Yeah, 1803 is buggy, 1809 isn't?, it depends on what is important to you. Galaxy may be waiting to see what MS has up their sleeve before releasing an update and possibly having to do it again.

Not rolling back because I have at least one game that uses Nvidia cards' latest RTX features. I'm just waiting for the cumulative patch that will come out for those who already have the bugged 1809 version. Well, I'll just wait for FMM 1.0.4.5 to come out.

**Comment by HackinSpock** [comment]
> > Hate typing, I should have expanded on this. like my prior thread said, I rolled back to 1803. The 1809 is still being processed by MS, but you can still update windows at this point. For those whom wish to wait till all the FMM issues are dealt with should be patient if they do not roll back. Yeah, 1803 is buggy, 1809 isn't?, it depends on what is important to you. Galaxy may be waiting to see what MS has up their sleeve before releasing an update and possibly having to do it again.
> 
> Not rolling back because I have at least one game that uses Nvidia cards' latest RTX features. I'm just waiting for the cumulative patch that will come out for those who already have the bugged 1809 version. Well, I'll just wait for FMM 1.0.4.5 to come out.

Yeh, I am waiting for the patch too. I am new to this mod manager, but does GalaxyEham usually come out with a new update each month?

**Comment by lKobi** [comment]
Please be patient guys, we already got confirmation a fix is being worked on, it would be unwise to release it now since update 1809 is being reworked by Microsoft (has also been removed from their Update Servers).

Anyone who got update 1809 did it manually, as Microsoft didn't automatically provide that update (and has also suggested anyone who has the files, to not install it).

Considering we already in November, it would be wise to rollback, else just wait.

**Comment by Rcj230** [comment]
> 
> 
> Please be patient guys, we already got confirmation a fix is being worked on, it would be unwise to release it now since update 1809 is being reworked by Microsoft (has also been removed from their Update Servers).
> 
> Anyone who got update 1809 did it manually, as Microsoft didn't automatically provide that update (and has also suggested anyone who has the files, to not install it).
> 
> Considering we already in November, it would be wise to rollback, else just wait.

Not quite all true.
The 1809 update was "Pushed" onto my system on the night of Oct 3rd.
After opening this thread, I rolled back to 1803 a couple of days later. Then I locked out Windows updates for a month.

**Comment by lKobi** [comment]
> > Please be patient guys, we already got confirmation a fix is being worked on, it would be unwise to release it now since update 1809 is being reworked by Microsoft (has also been removed from their Update Servers).
> > Anyone who got update 1809 did it manually, as Microsoft didn't automatically provide that update (and has also suggested anyone who has the files, to not install it).
> > Considering we already in November, it would be wise to rollback, else just wait.
> 
> Not quite all true.
> The 1809 update was "Pushed" onto my system on the night of Oct 3rd.
> After opening this thread, I rolled back to 1803 a couple of days later. Then I locked out Windows updates for a month.

Sorry but no, Update 1809 wasn't pushed to anyone. You had to manually trigger the Update through Windows Update.

**Comment by Rcj230** [comment]
> 
> 
> > > Please be patient guys, we already got confirmation a fix is being worked on, it would be unwise to release it now since update 1809 is being reworked by Microsoft (has also been removed from their Update Servers).
> > > Anyone who got update 1809 did it manually, as Microsoft didn't automatically provide that update (and has also suggested anyone who has the files, to not install it).
> > > Considering we already in November, it would be wise to rollback, else just wait.
> > 
> > 
> > Not quite all true.
> > The 1809 update was "Pushed" onto my system on the night of Oct 3rd.
> > After opening this thread, I rolled back to 1803 a couple of days later. Then I locked out Windows updates for a month.
> 
> Sorry but no, Update 1809 wasn't pushed to anyone. You had to manually trigger the Update through Windows Update.

I may have been too busy gaming to the see notification item in the tray, when I shut my system down it installed.

**Comment by Slayer5934** [comment]
Windows LTSC is what your looking for :)

**Comment by lKobi** [comment]
> > > > Please be patient guys, we already got confirmation a fix is being worked on, it would be unwise to release it now since update 1809 is being reworked by Microsoft (has also been removed from their Update Servers).
> > > > Anyone who got update 1809 did it manually, as Microsoft didn't automatically provide that update (and has also suggested anyone who has the files, to not install it).
> > > > Considering we already in November, it would be wise to rollback, else just wait.
> > > 
> > > 
> > > Not quite all true.
> > > The 1809 update was "Pushed" onto my system on the night of Oct 3rd.
> > > After opening this thread, I rolled back to 1803 a couple of days later. Then I locked out Windows updates for a month.
> > 
> > 
> > Sorry but no, Update 1809 wasn't pushed to anyone. You had to manually trigger the Update through Windows Update.
> 
> Yeah, like many, I have auto updates enabled. I may have been too busy gaming to see the notification item in the tray. When I shut my system down, it installed. Am I missing a setting I could enable besides disabling updates every 35 days?

Windows 10 Build 1809 didn't install through Automatic Updates as I already said, even though it may sound confusing, there's a huge difference between triggering the Windows Update and let it Auto Update.

No one was updated to Build 1809 without triggering the Windows Update manually, as the Update wasn't being rolled out yet.

**Comment by Rcj230** [comment]
> 
> 
> > > > > Please be patient guys, we already got confirmation a fix is being worked on, it would be unwise to release it now since update 1809 is being reworked by Microsoft (has also been removed from their Update Servers).
> > > > > Anyone who got update 1809 did it manually, as Microsoft didn't automatically provide that update (and has also suggested anyone who has the files, to not install it).
> > > > > Considering we already in November, it would be wise to rollback, else just wait.
> > > > 
> > > > 
> > > > Not quite all true.
> > > > The 1809 update was "Pushed" onto my system on the night of Oct 3rd.
> > > > After opening this thread, I rolled back to 1803 a couple of days later. Then I locked out Windows updates for a month.
> > > 
> > > 
> > > Sorry but no, Update 1809 wasn't pushed to anyone. You had to manually trigger the Update through Windows Update.
> > 
> > 
> > Yeah, like many, I have auto updates enabled. I may have been too busy gaming to see the notification item in the tray. When I shut my system down, it installed. Am I missing a setting I could enable besides disabling updates every 35 days?
> 
> Windows 10 Build 1809 didn't install through Automatic Updates as I already said, even though it may sound confusing, there's a huge difference between triggering the Windows Update and let it Auto Update.
> 
> No one was updated to Build 1809 without triggering the Windows Update manually, as the Update wasn't being rolled out yet.
> 
> In fact I was even forced to Download the ISO manually to even install the Update on a Test Machine, as it was not available even through Manual Trigger on Windows Update when I did it.

Thank you all for the helpful comments.

This was NOT manual.
http://www.mediafire.com/view/bzqx6wedl3wd2dj/Updates.jpg/file

Do any of us work for MS, did we have a hand in the 1809 update process?
Do we believe everything we read on the net?, then here;

Worst Windows 10 version ever? Microsoft's terrible, horrible, no good, very bad October

Microsoft released the Windows 10 October 2018 Update on October 2, then pulled it days later. Now, with November fast approaching, the update has still not been re-released. Where's the problem? And will it happen again?
Ed Bott

By Ed Bott for The Ed Bott Report | October 26, 2018 -- 12:52 GMT (05:52 PDT) | Topic: Microsoft

Thanks all

**Comment by lKobi** [comment]
> > > > > > Please be patient guys, we already got confirmation a fix is being worked on, it would be unwise to release it now since update 1809 is being reworked by Microsoft (has also been removed from their Update Servers).
> > > > > > Anyone who got update 1809 did it manually, as Microsoft didn't automatically provide that update (and has also suggested anyone who has the files, to not install it).
> > > > > > Considering we already in November, it would be wise to rollback, else just wait.
> > > > > 
> > > > > 
> > > > > Not quite all true.
> > > > > The 1809 update was "Pushed" onto my system on the night of Oct 3rd.
> > > > > After opening this thread, I rolled back to 1803 a couple of days later. Then I locked out Windows updates for a month.
> > > > 
> > > > 
> > > > Sorry but no, Update 1809 wasn't pushed to anyone. You had to manually trigger the Update through Windows Update.
> > > 
> > > 
> > > Yeah, like many, I have auto updates enabled. I may have been too busy gaming to see the notification item in the tray. When I shut my system down, it installed. Am I missing a setting I could enable besides disabling updates every 35 days?
> > 
> > 
> > Windows 10 Build 1809 didn't install through Automatic Updates as I already said, even though it may sound confusing, there's a huge difference between triggering the Windows Update and let it Auto Update.
> > No one was updated to Build 1809 without triggering the Windows Update manually, as the Update wasn't being rolled out yet.
> > In fact I was even forced to Download the ISO manually to even install the Update on a Test Machine, as it was not available even through Manual Trigger on Windows Update when I did it.
> 
> Thank you all for the helpful comments.
> 
> This was NOT manual.
> http://www.mediafire.com/view/bzqx6wedl3wd2dj/Updates.jpg/file
> 
> Do any of us work for MS, did we have a hand in the 1809 update process?
> Do we believe everything we read on the net?, then here;
> 
> Worst Windows 10 version ever? Microsoft's terrible, horrible, no good, very bad October
> 
> Microsoft released the Windows 10 October 2018 Update on October 2, then pulled it days later. Now, with November fast approaching, the update has still not been re-released. Where's the problem? And will it happen again?
> Ed Bott
> 
> By Ed Bott for The Ed Bott Report | October 26, 2018 -- 12:52 GMT (05:52 PDT) | Topic: Microsoft
> 
> Thanks all

I'm certainly I'm more of an Insider on Microsoft than you, especially when I manage over 500 PCs on multiple companies.

Regardless of your claims and believes, Windows 10 October Update was never automatic, it had to be manually triggered on Windows Update.

The automatic rollout was actually going to start a week after, but never reached that far as the Update was pulled.

**Comment by Rcj230** [comment]
> I certainly I'm more of an Insider on Microsoft than you, especially when I manage over 500 PCs on multiple companies.
> 
> Regardless of your claims and believes, Windows 10 October Update was never automatic, it had to be manually triggered on Windows Update.
> 
> The automatic rollout was actually going to start a week after, but never reached that far as the Update was pulled.
> 
> **It always been like that, as the automatic rollout always starts a week later.**

Look, I apologize if you are getting aggravated with me.
I lay no claim to being educated or smart, I realize you have far more experience than I.
I know of your reputation and knowledge.
I just wanted to know(Simply) how, while I was playing MEA did I trigger an update to 1809. I may have ignored "Focus Assistant" while playing, but it was there when I quit MEA and shut down. 

Sorry, damage done.
Let's not waste any more of anyone's time here on my ignorance.

**Comment by GalaxyEham** [comment]
No comment in 27 days, I think its fair to say that this issue has ran its course. With the latest update of the tools, the issue of 1809 update (regardless if it was ever deployed or not) has been resolved, as well as all future Insider versions for now.
