### ISSUE TITLE
Mirror´s Edge: Catalyst not launching

### ISSUE THREAD

**Issue by KeyMerVin** [GalaxyEham/FrostyToolSuite#133]
Hi, this is a issue that affected me since the first try on WIndows 10 Insider to now, on the October Update Stable

Frosty Mod Manager on the newer (even the newest 1.4.4) does not launch Mirror´s Edge Catalyst, with or without mods; makes the game´s proccess start and after a few seconds, it dissapears, and game is never shown on the screen

The Mod Editor cannot launch the game, either

In older versions of the Mod Manager, from 1.3 I think, the game launcher without mods, but not with them. I´ve tried many things; ownership, compatibility mode, ModData erasing, bcrypt.dll, one mod or other, etc, nothing is worked.

I´ve been adviced to downgrade the game´s version. I´ll try and see if it works, and tell

Thanks

**Comment by GalaxyEham** [comment]
Aware and resolved, fix will be in 1.0.4.5
