### ISSUE TITLE
value cannot be null

### ISSUE THREAD

**Issue by cwgaming** [GalaxyEham/FrostyToolSuite#135]
bei System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
   bei FrostySdk.Managers.oTnDRibmoUMJVroiwDtEwTiRsAbaEFqWRRd.ATOkMxAhhVlLMstp(Boolean YdwQTQljJSPsfGrhArhMHUXytQvssuAxPpNN)
   bei FrostyEditor.Windows.SplashWindow.<>c__DisplayClass4_0.<alwnINbrtuuSnITLuIfVoXOYlSxMDRs>b__0()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FrostyEditor.Windows.SplashWindow.<alwnINbrtuuSnITLuIfVoXOYlSxMDRs>d__4.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FrostyEditor.Windows.SplashWindow.<DijCPsYUuARWolJlFcifgEsvDkuUkXoq>d__2.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
Well considering u provided absolutely zero information on how the error occurred, let me just take a wild guess and say, u either didnt enter a encryption key when asked, or u entered the wrong one.

**Comment by cwgaming** [comment]
"An unhandled exception has occurred"

**Comment by GalaxyEham** [comment]
Really? my last message didnt sink in? how am I supposed to help, if your not even going to attempt to provide any info other than a generic error. You know what, im closing this issue, open a new one and do it properly, if you continue to provide no info, i will continue to close
