### ISSUE TITLE
where do we leave feedback / requests?

### ISSUE THREAD

**Issue by crimsonstarr** [GalaxyEham/FrostyToolSuite#137]
can you implement a search by type for data explorer?

say i want to search for items with the type being LensFlareEntityData or LensFlareBlueprint

**Comment by crimsonstarr** [comment]
please add an import mod feature so we can import other players mods in the editor and update them to work on latest game verion.

**Comment by GalaxyEham** [comment]
searching inside assets is planned for the future already, however there is a lot that needs to happen before that can be done.
