### ISSUE TITLE
SWBF2 Frosty Mod Manager just not launching game!

### ISSUE THREAD

**Issue by DartSnack** [GalaxyEham/FrostyToolSuite#140]
Befor it just stop launching i put file CryptBase.dll on the path Programm Files (x86)/ Origin Games / STAR WARS Battlefront II. Befor this was a crash "An unhandled exception has occured". So i dunno what to do. Help me please. Thank you in advance!

**Comment by MattGTX** [comment]
@DartSnack Can you send me the full log of the error? Bc @GalaxyEham isn't competente enough to answer to this Type of error
