### ISSUE TITLE
couldn't find anywhere else to ask this

### ISSUE THREAD

**Issue by rancorx2** [GalaxyEham/FrostyToolSuite#141]
does anyone have a copy of the galactic assault in arcade mod they can share? or can the author please unhide it's mod page on nexusmods? would like a copy of the frosty ed project file if possible to have a tinker.

**Comment by rancorx2** [comment]
GalaxyMan2015 please unhide your mod @rancorx2 https://www.nexusmods.com/starwarsbattlefront22017/mods/366/

**Comment by GalaxyEham** [comment]
Theres a reason its hidden, because it is irreversibly broken. One of the updates completely changed the way the SP menus work, and so therefore all this mod would do is crash your game, even the project is useless, and I have never found the time to recreate it.

**Comment by rancorx2** [comment]
can you at least give me a copy of the project file(s) so i can have a look? as i'm sick of waiting for dice to improve the game.
