### ISSUE TITLE
can you at least give me a copy of the project file(s) so i can have a look? as i'm sick of waiting for dice to improve the game.

### ISSUE THREAD

**Issue by rancorx2** [GalaxyEham/FrostyToolSuite#142]
_Originally posted by @rancorx2 in https://github.com/GalaxyEham/FrostyToolSuite/issues/141#issuecomment-443670288_

**Comment by GalaxyEham** [comment]
that would be completely useless, as i stated, they changed the way its all handled, the project basically does not even work at all. Plus in my latest purging of data it was removed.
