### ISSUE TITLE
(Star Wars Battlefront, 2015) Mods wont load up modded HUD textures

### ISSUE THREAD

**Issue by HeyItsGreedo** [GalaxyEham/FrostyToolSuite#145]
Some will load up the game fine but once a certain texture is loaded it closes my game without warning. A mod editing the binoculars weapon load battlefront but its on the loading screen and eventually a "DirectX Error" saying "DirectX function "device->CreateTexture2D( &texDesc,desc.subResourceCount != 0 ? reinterpret_cast<constD3D11_SUBRESOURCE*>(desc.subResourceData) : 0, &texture->m_texture2d)" failed with E_INVALIDARG ("An invalid parameter was passed to the returning function."). GPU: "Intel(R) HD Graphics 5500", Driver 20.19.15.4531 09/29/2016 00:00:00" and for hero pictures it just crashed (with this message aswell, I think)

**Comment by GalaxyEham** [comment]
Either you used the wrong format (Frosty wont complain, but the game will) or you imported a texture with mips, both of these are known to cause that error if its a UI texture. However if you are using the latest version 1.0.4.5 and are importing PNG/TGA or HDR, then I will take a look, altho my testing showed no issues with UI or regular textures.

**Comment by HeyItsGreedo** [comment]
whats a wrong format?
