### ISSUE TITLE
SWBF2 - Crash on load

### ISSUE THREAD

**Issue by MatteoH2O** [GalaxyEham/FrostyToolSuite#158]
Game: Star Wars Battlefront II with last DLC at the time of writing (Absolute Supremacy)
Editor: Frosty Editor 1.0.5
OS: Windows 7 Home Premium 64 bit
GPU: GTX 1070 3GB VRAM

How to replicate:

1. Install SWBF2 with Absolute Supremacy DLC

2. Create a new configuration using Frosty Editor 1.0.5 and selecting starwarsbattlefrontii.exe

3. The load should fail with an error similar to this: [crashlog.txt](https://github.com/GalaxyEham/FrostyToolSuite/files/3085199/crashlog.txt)

P.S.: in case you can't read italian:

- **Le dimensioni della matrice hanno superato l'intervallo supportato**
means
**The matrix size has exceeded the supported interval**

- **Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione**
means
**End of stack's trace from previous position from where the exception was generated**

Probably not what you would actually get in english but I think it's pretty close.

**Comment by GalaxyEham** [comment]
Please read the stickied note before raising issues, I said I would close any that do not follow the template.
