### ISSUE TITLE
ME:Andromeda launch issue

### ISSUE THREAD

**Issue by Reaper507** [GalaxyEham/FrostyToolSuite#160]
Your tool doesn't use bcrypt.dll anymore, instead it uses cryptbase.dll, so old solution (on nexus page) is out of date. ME:Andromeda won't start via FrostyMM, just hangs in the process list.

I used FrostyMM 1.0.3.a4 as temporal solution for launching ME:Andromeda via the manager.

Win7/64bit

**Comment by GalaxyEham** [comment]
Old versions should not be used, and bcrypt should not be used anymore. If game does not launch with the newer versions, your issue is permissions, please fill out the template properly as per the sticky to get help.
