### ISSUE TITLE
Lanuch button not working with mods.

### ISSUE THREAD

**Issue by Uzio08** [GalaxyEham/FrostyToolSuite#17]
When i click lanuch button in Frosty Editor or Frosty Mod Manager with mods enable game na lanuching.

**Comment by GalaxyEham** [comment]
please provide more details

**Comment by Uzio08** [comment]
When I open frosty mod manager, I apply for example Messi Brown hair mod (https://i.imgur.com/kh1usxw.png)
and click lanuch button game not opening (A window with fifaconfig is displayed just for a moment https://i.imgur.com/wLB5GN2.png) . When I click lanuch button without mod (https://i.imgur.com/twswlDn.png) game working.

**Comment by GalaxyEham** [comment]
try replacing the the bcrypt.dll in the ThirdParty directory of the Tools directory (ie. Frosty Mod Manager or Frosty Editor / ThirdParty) with the bcrypt.dll from v1.0.2b. There is a known issue for some users with the new bcrypt in the alpha.

**Comment by GalaxyEham** [comment]
Unfortunately then there is nothing else i can do, u have a permissions/access rights issue that u need to solve at ur end.

**Comment by Uzio08** [comment]
I;m waitng 11 months for that and not working :(

**Comment by Uzio08** [comment]
You know how to sets permission?

**Comment by GalaxyEham** [comment]
Every users configuration is different, so you'll have to figure it out at your end.

**Comment by Uzio08** [comment]
But where is the permission seetings?

**Comment by GalaxyEham** [comment]
Google it.

**Comment by Uzio08** [comment]
OK

**Comment by darkmyst** [comment]
I have the same problem with Mass Effect: Andromeda. With mods, it launches the ME:A executable which gets up to about 80m of memory usage and just stops. The game window never opens. Without mods, the game launches normally. Using the older bcrypt.dll doesn't change anything.

**Comment by GalaxyEham** [comment]
Same resolution as above, u have a permissions/user rights issue that you will need to resolve at ur end.
