### ISSUE TITLE
Paths and classes not editable

### ISSUE THREAD

**Issue by oomek** [GalaxyEham/FrostyToolSuite#2]
I'm trying to improve Scopes Unscoped mod for MEA. The autor of this mod (null)'ed some strings like for example game>weapons>mods>ScopeUiOverride but only few types of elements I can actually change in your editor like tick boxes, numeric values or combo boxes. Everything else does not react to clicks. Is it a limitation of your tool or a bug?

**Comment by GalaxyEham** [comment]
limitation, check the latest version (v1.0.2) arrays and refs are now editable.

**Comment by oomek** [comment]
Awesome! I'm able to finish my mod now. Thanks.
