### ISSUE TITLE
Models exported have distorted UVs

### ISSUE THREAD

**Issue by vanya-krut98** [GalaxyEham/FrostyToolSuite#23]
Browsing through Battlefront 2015's models, I noticed a lot of them have distorted, messed up UVs while previewing. I thought it was just a problem with the preview inside FrostyEditor, but when imported into 3Ds Max, the problem is still there.

Here's a screenshot: https://i.imgur.com/U2ddcYx.jpg

**Comment by GalaxyEham** [comment]
They are not distorted, SWBF employs multiple UV channels for multiple textures, so in some cases it'll use UV0 for diffuse, and UV1 for normals, etc. This is shader specific and the Frosty previewer cannot determine this info. On export all texture coordinates are included, so just check the other ones against the diffuse until u find the one that matches.

**Comment by vanya-krut98** [comment]
Ah, okay. 

Thank you.
