### ISSUE TITLE
How to import 3D models into FrostyEditor?

### ISSUE THREAD

**Issue by SalvoSoftware** [GalaxyEham/FrostyToolSuite#25]
I'm making a mod for FIFA 17 and, after clicking on a mesh, I can export this mesh to a .fbx file.
The problem is that the import button is deactivated, is that correct?
I want to replace the old mesh with the new one but I have no idea how to do it!

**Comment by GalaxyEham** [comment]
you can't, this is not supported yet.

**Comment by kylerwinters** [comment]
@SalvoSoftware We would like to talk to you about acquiring your GitHub username. Please shoot us a email at hello@salvosoftware.com

**Comment by kylerwinters** [comment]
@GalaxyEham Sorry about the spam. This is one and only way I have to contact @SalvoSoftware
