### ISSUE TITLE
Provide source code

### ISSUE THREAD

**Issue by m35** [GalaxyEham/FrostyToolSuite#30]
I would like the source code to explore and extend this tool. I spent time [reverse-engineering the original Mirror's Edge](http://erictheturtle.blogspot.com/search/label/Mirror%27s%20Edge). I was hoping to do the same with Mirror's Edge Catalyst.

**Comment by AnonBaiter** [comment]
[https://www.red-gate.com/products/dotnet-development/reflector/index](url)
Use this instead.

**Comment by GalaxyEham** [comment]
The source will remain closed. Eventually I plan on moving to a more open profiles system, where ppl can contribute information/code specific to a game profile.
