### ISSUE TITLE
An Unhandled Exception has Occurred, The file exists

### ISSUE THREAD

**Issue by ezequil97** [GalaxyEham/FrostyToolSuite#31]
I am having an issue on FrostyModManager, I am using FrostyModManager_1.0.3alpha3, I downloaded and installed the 3 components, which are "Microsoft .NET Framework 4.6.2", "Microsoft DirectX® End-User Runtime", and "Visual C++ 2017 redistributable". Everytime I run FrostyModManager as Administration, it always shows up "An Unhandled Exception has Occurred". I am a Windows 7 user, and I plays Steampunk Cracked version FIFA 17. Please help me out, I really wanted to apply mod into my FIFA 17.
Here is the error image:
![2](https://user-images.githubusercontent.com/33365633/32402441-32972a66-c15f-11e7-80bc-a56c5cb065d2.JPG)

**Comment by GalaxyEham** [comment]
Do a google search, ive never seen that issue before, and it doesnt appear to be related to Frosty at all, as it mentions trying to load a cursor. I suspect you are missing some kind of dependency or u have a broken .NET Framework installation.
