### ISSUE TITLE
Frosty Mod Manager Issue (Not Loading with mods active)

### ISSUE THREAD

**Issue by TanyaeNorth** [GalaxyEham/FrostyToolSuite#34]
Frosty Mod Manager Issue (Not Loading with mods active)

I have been dealing with an issue with the newest release(1.0.3alpha4) of the frosty mod manager(not the editor). This may just be a small overlook on my part but any help is much appreciated (:

The issue seems to only be on the manager as the editor runs fine whether the files have been changed or not, however whenever I launch the manager with mods activated origin opens up then closes and opens then nothing happens(I have waited for roughly 20 minutes before giving up). Also, nothing shows up in the task manager to prove that the game is trying to launch. There is no error list that would normally show up making it harder to further source the problem but I will try to provide you with the most details I can including a link to a video of the problem.

Details
- The game won't launch with mods active but will if there are no mods active
- The game I'm running is Star Wars Battlefront EA(2015) 
- The error only occurs on the manager
- The version is 1.0.3alpha4
- There is no error screen after launching the 

Link to video download
[MAIN LINK](https://mega.nz/fm/ln4TlRiS) 
[EXPRESS LINK](https://mega.nz/#!cm4GGLAB!kbLa8MvBcEKnOE4OnqiGQGa9OrOClLjDLj3soaAEGgc) 
If it asks you for a Decryption key use this "!kbLa8MvBcEKnOE4OnqiGQGa9OrOClLjDLj3soaAEGgc"

Thank you for reading my issue if you need to contact my Gmail is
TanyaeNorth@gmail.com

Kind regards,
Tanyae North

**Comment by Uzio08** [comment]
Same :(

**Comment by GalaxyEham** [comment]
Make sure you take ownership of the game directory and that you have full write permissions. Also make sure to run the mod manager as admin. Delete the ModData directory and bcrypt.dll from the game directory before doing this.

**Comment by TanyaeNorth** [comment]
I have tried deleting the bcrypt.dll in both the manager itself and the actual game files as well as the ModData folder in the game files and running the manager as admin but it still does not seem to work?

Something I found out is that it works on my C drive rather than my D drive but I don't have enough storage to put it in my C drive.

Hopefully, you can help out with this issue.

Kind regards,
[Tanyae North](TanyaeNorth@gmail.com)

**Comment by GalaxyEham** [comment]
Then it is an issue with permissions/ownership. If it works in one location and not another, it comes down to your configuration.

**Comment by MattGTX** [comment]
@GalaxyEham  For me, the Frosty works with all games but SWBF2. When I try to select it, I have this error. What should I do?

Nome de caminho vazio não é válido.

   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   em FrostySdk.hbDInlQMRUGMPLqYDjQOEVHDfCQ.ieJivyCWYhcMiiuWROCLrmYSoRIJOTrRsByEkWS(qQmnXYHsegLTyJGfbsNUleeqwC FgWUHCuDeFohHHJLUCR)
   em FrostyModManager.MainWindow.bncNbrbUhsNtasOwiRT(Object QpxpJEYByScUPTcjxFpEhQPT, EventArgs LrPiUbEsjnBGjVvWkjJuwxoEURfvWKWAPEqnD)
   em System.Windows.Window.OnContentRendered(EventArgs e)
   em System.Windows.Window.<PostContentRendered>b__202_0(Object unused)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MattGTX** [comment]
And Yes, I executed it with administrator rights

**Comment by MattGTX** [comment]
Yesterday it was working fine but not anymore
