### ISSUE TITLE
Error "An unhandled exception has occurred"

### ISSUE THREAD

**Issue by brunoflahexa** [GalaxyEham/FrostyToolSuite#36]
Here was the error. My Fifa 18 is not original. Does this work only in the original FIFA 18?

![](https://uploads.disquscdn.com/images/0e34bcae07020d4fb66f9cb71782177d1a929f14407532aab00887d05c45f348.png)
Good evening!

**Comment by pargsoft** [comment]
This is happening for a lot of people, not just you.

**Comment by GalaxyEham** [comment]
This is a known issue, and will be resolved in the next update
