### ISSUE TITLE
bcrypt.dll / modding will not work on certain PCs

### ISSUE THREAD

**Issue by pargsoft** [GalaxyEham/FrostyToolSuite#37]
Hi all,

(paulv2k4 here)

There are still some issues occurring with bcrypt, initfs, modding in FIFA 18. (FIFA 17 was fine by the way)

[http://www.soccergaming.com/index.php?threads/bcrypt-dll.6463909/](Link to SG Forum with my thread with discussion on what the issue could be.)

This is only an issue on my **Laptop**. (does occur to some peoples PCs too)

Specification of **Laptop**:

Operating System: Windows 10 Pro 64-bit (10.0, Build 15063) (15063.rs2_release.170317-1834)
Processor: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 CPUs), ~2.6GHz
Memory: 8192MB RAM
Available OS Memory: 8082MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Graphics: Intel 530 & Nvidia 960m 
Game Dir: F:\FIFA 18

Game installed to Non-Windows Drive. Full Permission given. (EVERYBODY FULL ACCESS). No Unblock Option Given.

Specification of **PC** (Always works):

Operating System: Windows 10 Pro 64-bit (10.0, Build 15063) (15063.rs2_release.170317-1834)
Processor: AMD 750K
Memory: 16GB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Graphics: Nvidia 1060 
Game Dir: F:\FIFA 18

Game installed to Non-Windows Drive. Full Permission given. (EVERYBODY FULL ACCESS). No Unblock Option Given.

A summary of my attempts to problem solve,

- I have tried multiple versions of the bcrypt.dll file
- I have tried multiple versions of the initfs file
- FrostyEditor worked fine for me in FIFA 17 (which included bcrypt.dll)
- I have all the recommended MS components
- I am updated to the latest version of FIFA 18 (through Origin, legal version)

- Attempted on Windows 10 Home 1703
- Attempted on Windows 10 Home - Fall update
- Attempted on Windows 10 Pro 1703
- Attempted on Windows 10 Pro 1709
- Both machines identical Windows 10 Pro

- All Microsoft frameworks are up to date. Visual Studio is installed on both machines (attempted without them first!). 

- I have turned off Windows Defender through Group Policy and Services. Makes no difference.

- There is no other applications on the Laptop to affect the game. No Riva. No Geforce Experience.

Any more information or tests I can carry out, please let me know.

Regards,

paulv2k4 (PARGSoft is company name)

**Comment by TheAwesomeGem** [comment]
I can confirm this issue!

**Comment by GalaxyEham** [comment]
This will always be an issue, there is something preventing you from using the modified bcrypt, regardless of what you have checked, there is still some setting somewhere preventing it. Unfortunately due to the numerous configurations out there, I cannot solve this issue 100%. As it works for the majority of users, and I have rolled back to the v1.0.2b bcrypt.dll, this is the most I can do for now.
