### ISSUE TITLE
Can't launch Dragon Age: Inquisition profile

### ISSUE THREAD

**Issue by HankJohnson** [GalaxyEham/FrostyToolSuite#38]
Latest alpha (1.0.3a4) can't launch a Dragon Age: Inquisition. It can launch a Mass Effect: Anromeda profile. Previous version (1.0.3a3) could launch DA:I profile.

![b](https://user-images.githubusercontent.com/33547881/32659789-55fffd08-c631-11e7-96c7-bec868f10bcc.PNG)

**Comment by GalaxyEham** [comment]
Is your game the english version? is it fully up to date? is the executable named DragonAgeInquisition.exe?

**Comment by HankJohnson** [comment]
Sorry I haven't replied earlier.

> Is your game the english version?

It is multi-language version. I'm playing russian, but english is also there, along with many other languages.

> is it fully up to date?

It's GotY.

> is the executable named DragonAgeInquisition.exe?

Yes.

**Comment by HankJohnson** [comment]
Same error in recent update (1.0.3).

**Comment by Ruuuuuuh** [comment]
Same here.

**Comment by Archeolonio** [comment]
Any solution?
