### ISSUE TITLE
stuck at copying patch resources

### ISSUE THREAD

**Issue by Dulana57** [GalaxyEham/FrostyToolSuite#4]
Whenever I press launch it's stuck at this and does load the game
![screenshot 2017-07-03 20 26 15](https://user-images.githubusercontent.com/13797470/27810898-e351eca8-602d-11e7-8b5a-31535612776a.png)

**Comment by GalaxyEham** [comment]
Give it time. It has to copy 10gb of data, it aint gonna happen quickly.

**Comment by GalaxyEham** [comment]
Closing this issue as I have not heard back from you in 7 days
