### ISSUE TITLE
FIFA 18

### ISSUE THREAD

**Issue by Krrypt0n** [GalaxyEham/FrostyToolSuite#42]
Hi, can someone explain me how to unlock those encrypted files? https://imgur.com/a/EqK5e

**Comment by lucadelma** [comment]
non riesco ad entrare. come devo fare? che codice devo mettere?

**Comment by lucadelma** [comment]
La dimensione della chiave specificata non è valida per questo algoritmo
mi da questo errore fifa 18 perche'?

**Comment by Redmessi** [comment]
interesting that it is in there :/

**Comment by GalaxyEham** [comment]
Those encrypted assets cannot be unencrypted, they require an additional key that is unknown at this time, its usually associated with online content.
