### ISSUE TITLE
Frosty Editor cannot launch the game after title update 5

### ISSUE THREAD

**Issue by LycenYao** [GalaxyEham/FrostyToolSuite#45]
The exception was
Cannot find 
D:\Program Files (x86)\Origin Games\FIFA 18\\moddata\patch\win32/superbundlelayout/fifa_installpackage_00/en/cas.cat

This path is quite strange. Maybe the path strings were concatenated incorrectly.

**Comment by jediProgramer** [comment]
Yes i have same issue ... any fix for this trouble???

**Comment by KampfKeks510** [comment]
i have the same issue:

Ein Teil des Pfades "S:\Spiele\Origin\FIFA 18\\moddata\patch\win32/superbundlelayout/fifa_installpackage_00/de/cas.cat" konnte nicht gefunden werden.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei System.IO.FileInfo.CopyTo(String destFileName)
   bei Frosty.ModSupport.FrostyModExecutor.⁯​‍⁭‮‬⁪‮‬⁯⁪⁯⁮‭‎‮⁬‮‏‬⁯​‫⁪​‍‮‮‍⁮⁭‭⁭​⁭‪⁫⁫⁮‏‮.‭‍⁫⁪‬⁪⁬‪‪‏​‪⁬⁭⁭‌⁯⁭⁮⁭‌‪‪‬‏⁫‍⁪⁭⁫‌‪⁬‏​‮⁫⁬‌‎‮()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Frosty.ModSupport.FrostyModExecutor.PL/4V#5m#OJ3zFX4X!nL8 z}(.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
Delete the ModData directory in the Fifa18 game directory, Unfortunately fifa18 does not update the internal patch version when they release an update, so the mod manager does not know an update has occurred, leaving things in an inconsistent state. Deleting the ModData directory should resolve this.

**Comment by jediProgramer** [comment]
i'm delete ModData directory  in fifa 18 game directory and still error:

Value cannot be null.
Parameter name: value

   at System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
   at FrostySdk.FileSystem.‫‭‌‭‫‬⁪‏‭‎⁮⁯‪‎‎‫⁪‏‫⁭⁭‍‍⁯‍⁬‫‫‌‬⁪‍‏⁮⁫​‏⁮‌⁫‮(Byte[] )
   at FrostySdk.FileSystem.Initialize(Byte[] key)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by LycenYao** [comment]
@GalaxyEham Yes, it works again. Thank you for the solution.
