### ISSUE TITLE
Mod is working good at Editor but not working on Mod Manager

### ISSUE THREAD

**Issue by halilyc** [GalaxyEham/FrostyToolSuite#46]
Hi bro, thanks for your effort firstly :) 
So much mod is working good but when I made Press Start Screen mod for FIFA18, its working perfect when I launch it with Frosty Editor but I exported it as a mod and enabled it on Mod Manager, game was crashed. 
Some mods working good, some mods not working on Frosty Manager, its interesting. 

Maybe you know Mod Manager is not working already when you released alpha 4, some guys fixed it with new dll file inifits.

**Comment by GalaxyEham** [comment]
This is a known issue that is being investigated
