### ISSUE TITLE
Error Opening Fifa.EXE

### ISSUE THREAD

**Issue by deyvsonlipe** [GalaxyEham/FrostyToolSuite#51]
![erro](https://user-images.githubusercontent.com/34520538/33957111-d3940c68-e027-11e7-8711-e6aa200788e6.jpg)

when you run the frosty editor by selecting fifa.exe, it displays an error message: "THERE WAS AN ERROR WHEN TRYING TO LOAD THE SELECTED GAME."

How to solve this problem?

**Comment by GalaxyEham** [comment]
Which fifa? the exe must be named Fifa17.exe or Fifa18.exe. No other derivatives will work.

**Comment by deyvsonlipe** [comment]
Fifa18.exe
