### ISSUE TITLE
fifa 18 an unhandled exception has occured 

### ISSUE THREAD

**Issue by jaiy2kkumar** [GalaxyEham/FrostyToolSuite#52]
![fifa 18 error](https://user-images.githubusercontent.com/34616815/34077186-0ac6d6ae-e323-11e7-8f70-590a69172045.jpg)

I selected the fifa 18. exe . when i try to launch the game from frosty mod manager i get the above error  please help

**Comment by jaiy2kkumar** [comment]
G:\origin games\FIFA 18
Windows 10 home edition
 i tried running the editor and manager as admin
 i have taken full control of the ownership of the game folder
lanuage is english regional settings is india

**Comment by GalaxyEham** [comment]
This is a known issue and will be resolved in the next update
