### ISSUE TITLE
We want to be aware of developments

### ISSUE THREAD

**Issue by halilyc** [GalaxyEham/FrostyToolSuite#53]
Hi master, I hope you are good :) I know it is hard to solve Frostbite structure and you are trying to find way solve 3D model import and adding extra files but we cant follow any forum or site for be aware of developments. If you write somethings about development situation, we will be happy master :) 
Thank you for everything you've done so far, have a good day :)

**Comment by GalaxyEham** [comment]
In the editor itself is a link to the Frosty Server discord. This is where I post any and all updates, including WIP screenshots. Ive also pasted the link in here:

https://discord.gg/ksdmeEG
