### ISSUE TITLE
switch between two .exe

### ISSUE THREAD

**Issue by Choubi37** [GalaxyEham/FrostyToolSuite#55]
Hello

can we have the possibility to scan and open two different .exe ??
cuz as soon as we have scan one .. , i don't see where scan an other .exe in option ...

i want switch between SWBF1 exe and SWBF2 exe ...
regards

**Comment by GalaxyEham** [comment]
This is being considered, however a more elaborate profiles system will be the end result and therefore will take time to complete. For now, just copy the editor/mod manager to another directory and delete the INI file and pick the alternate executable.
