### ISSUE TITLE
FIFA 18 has stopped working

### ISSUE THREAD

**Issue by Barcafan11** [GalaxyEham/FrostyToolSuite#57]
bcrypt.dll (18kb) was working on v1.0.3alpha4. Tried everything to make bcrypt.dll (91kb) to work on v1.0.3. But every time it crash the games..I am using windows 7  ultimate. 64 bit operating system.  

Problem: FIFA 18 has stopped working
Problem details:

Problem Event Name:	BEX64
  Application Name:	FIFA18.exe
  Application Version:	1.0.0.0
  Application Timestamp:	5a16d9f7
  Fault Module Name:	StackHash_1dc2
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	0000000000000000
  Exception Code:	c0000005
  Exception Data:	0000000000000008
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	3081
  Additional Information 1:	1dc2
  Additional Information 2:	1dc22fb1de37d348f27e54dbb5278e7d
  Additional Information 3:	eae3
  Additional Information 4:	eae36a4b5ffb27c9d33117f4125a75c2

**Comment by moshiurrahman5555** [comment]
FIFA 18 has stopped working. What can i do!


Problem: FIFA 18 has stopped working
Problem details:

Problem Event Name:	BEX64
Application Name:	FIFA18.exe
Application Version:	1.0.0.0
Application Timestamp:	5a16d9f7
Fault Module Name:	StackHash_1dc2
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	00000000
Exception Offset:	0000000000000000
Exception Code:	c0000005
Exception Data:	0000000000000008
OS Version:	6.1.7601.2.1.0.256.1
Locale ID:	3081
Additional Information 1:	1dc2
Additional Information 2:	1dc22fb1de37d348f27e54dbb5278e7d
Additional Information 3:	eae3
Additional Information 4:	eae36a4b5ffb27c9d33117f4125a75c2
