### ISSUE TITLE
v1.0.3 Mass Effect Andromeda runs as a background process 

### ISSUE THREAD

**Issue by memmud15** [GalaxyEham/FrostyToolSuite#59]
i tried everything even using  older v1.0.2b bcrypt.dll and deleting ModData and bcrypt.dll from the game folder but to no avail!

**Comment by rshel555** [comment]
Exactly the same symptoms. I'd like to try to launch MEA with the 1.02 version, but haven't found it through Google search. No Google-fu, I suppose.
