### ISSUE TITLE
Frosty editor

### ISSUE THREAD

**Issue by Malin20** [GalaxyEham/FrostyToolSuite#61]
Frosty editor dont work with update 5 on fifa 18 please please fix it

**Comment by GalaxyEham** [comment]
be more descriptive. How am I supposed to do anything without any info what so ever.

**Comment by GalaxyEham** [comment]
and in saying that, if there is indeed an issue, it'll be fixed when its fixed, not when its demanded.

**Comment by Malin20** [comment]
can i pm you mate i really wanna txt with you

**Comment by Malin20** [comment]
i will said everything about the issue

**Comment by GalaxyEham** [comment]
No, just state the issue here, or go onto discord and report it in #troubleshooting

**Comment by Malin20** [comment]
what is the discord?
