### ISSUE TITLE
Fifa 18 frosty bug

### ISSUE THREAD

**Issue by Ozzain** [GalaxyEham/FrostyToolSuite#62]
![26235406_1610540115705468_1640301364_n](https://user-images.githubusercontent.com/35081925/34542529-43a70a26-f0dd-11e7-88af-59d0619bc0e1.jpg)

Get this after installing frosty manager and the patch fix, it says "an error has occured, we cant connect you to the ea servers to activate fifa 18 on this computer with your account, try again later" 

please help i really want the new faces :)

(on orgin)

**Comment by GalaxyEham** [comment]
Thats not an issue with the Frosty Toolsuite, thats an issue with your activation of the game.
