### ISSUE TITLE
When i press Launch nothing happens.

### ISSUE THREAD

**Issue by Simorss** [GalaxyEham/FrostyToolSuite#63]
When i press Launch the game just doesn't start.
But when i try to start it normally it works.
I've done a video so you can see if i do something wrong.
[Video.zip](https://github.com/GalaxyEham/FrostyToolSuite/files/1606967/Video.zip)
(sorry for the bad quality but GitHub allow only file smaller than 10MB)

**Comment by Mxxvn** [comment]
Hey, u need to take ownership from ur Fifa 18 main folder to get full access. check this and follow the steps. Works for me 
https://winaero.com/blog/how-to-take-ownership-and-get-full-access-to-files-and-folders-in-windows-10/
