### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ozzain** [GalaxyEham/FrostyToolSuite#64]
Are you supposed to be renamed by frosty when you use it on orgin? cause i got renamed at first, got scared of being hacked so i fixed it and got my name back and since then i havnt been able to use the mod manager, idk if thats the prob or not but if so pls tell me how to fix it

**Comment by GalaxyEham** [comment]
renamed? what. Frosty doesnt touch anything origin related what so ever.

**Comment by Sinsu** [comment]
Hello sir thank you for your frosty editor i have some problem, I want to translate the team name from English to Korean. i know how to change but when i try it is broken... Can you let me know if you don't mind..?
