### ISSUE TITLE
SWBF2 Always crashes unless using older bcrypt (18kb version)

### ISSUE THREAD

**Issue by diddykonga** [GalaxyEham/FrostyToolSuite#65]
Ive already done the steps written by the devs, Deleted ModData folder, and the bcrypt that was there, and just to make sure it wasnt a permissions issue, i took ownership of my ENTIRE Program Files folder, aswell as gave my self Full Control Permissions. None of these steps resolve the issue, still crashes with BEX64 event name. 

The only fix i have found is to download this bcrypt file that i found on discord (18kb version), but now i cant even find the link anymore, so if i ever lose the file ill be screwed lol

**Comment by GalaxyEham** [comment]
This is known, and the alpha4 bcrypt.dll should be used in replacement, not any older.
