### ISSUE TITLE
Nothing happens when I press launch.

### ISSUE THREAD

**Issue by gaaxure** [GalaxyEham/FrostyToolSuite#7]
After importing the desired mods and pressing the launch button in Mod manager nothing happens. PC just "thinks" for a few seconds and then nothing...

**Comment by GalaxyEham** [comment]
what game?

**Comment by gaaxure** [comment]
Mass effect: Andromeda. The process appears in the task manager for a few seconds and then just disappears. No crash message, no error, nothing.

**Comment by GalaxyEham** [comment]
try restarting origin. otherwise delete the ModData directory and bcrypt.dll from the MEA installl dir and try again

**Comment by gaaxure** [comment]
Deleting ModData helped, thx.
