### ISSUE TITLE
FIFA 18 - Career mode Crash

### ISSUE THREAD

**Issue by sikes92** [GalaxyEham/FrostyToolSuite#70]
I have modded FIFA 18's cmsettings.ini with Frosty Editor. 
I created a mod and use the mod manager to launch the game with the applied mod (edited cmsettings.ini).

I can start a new career and play without any issues WITH the edited cmsettings.ini,
BUT: As soon as i save my career and try to reload it, FIFA crashes to the desktop. 
It happens every time: I can start a new career, play without any problems until I save and try to load the next time...

Do you have any ideas on fixing the problem?
Thanks!

**Comment by GalaxyEham** [comment]
not a tools issue
