### ISSUE TITLE
An unhandled exception has ocurred 

### ISSUE THREAD

**Issue by efepe** [GalaxyEham/FrostyToolSuite#71]
No se puede encontrar una parte de la ruta de acceso 'C:\Program Files\FIFA18\\moddata\patch\win32/superbundlelayout/fifa_installpackage_00/nl/cas.cat'.

   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   en System.IO.FileInfo.CopyTo(String destFileName)
   en Frosty.ModSupport.FrostyModExecutor.⁪‮⁫⁮⁭‮‌‫⁮⁫‏⁫‫‌⁮‬‭‏‮⁯‬‎‌‭‮‏⁯⁯‏‌‪⁭⁯⁪⁮‭‮‬‫‌‮.⁯​⁬‫​‍​⁭‬⁮‭⁮‎‏‪⁬‎⁮‪‏‪⁬‬‌‮‎​‌‍⁯‪‮​⁪‭‍‭‪‬‍‮()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Frosty.ModSupport.FrostyModExecutor.'g{iqT;PR5)>:JK(mxeNr/JD.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

fifa 18 from skidrow, update 3, fifa work without frosty

thanks!

**Comment by rabbitofdeth** [comment]
I have this too.. so far no fix. :(

**Comment by Aveline457** [comment]
I have this too, first time running the Editor. What does it even mean??? No option but hit OK and it just closes...

**Comment by rabbitofdeth** [comment]
If you delete the mod data in your fifa 18 directory it fixes it. Did for me at least.


-------- Original message --------
