### ISSUE TITLE
Already Solved

### ISSUE THREAD

**Issue by toonicoopete** [GalaxyEham/FrostyToolSuite#74]
Every time I try to run Star Wars Battlefront 2 this error shows:

No se puede encontrar una parte de la ruta de acceso 'C:\Program Files (x86)\Origin Games\STAR WARS Battlefront II\\moddata\patch\win32/installation/initialexperience/cas.cat'.

   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   en System.IO.FileInfo.CopyTo(String destFileName)
   en Frosty.ModSupport.FrostyModExecutor.⁪‮⁫⁮⁭‮‌‫⁮⁫‏⁫‫‌⁮‬‭‏‮⁯‬‎‌‭‮‏⁯⁯‏‌‪⁭⁯⁪⁮‭‮‬‫‌‮.⁯​⁬‫​‍​⁭‬⁮‭⁮‎‏‪⁬‎⁮‪‏‪⁬‬‌‮‎​‌‍⁯‪‮​⁪‭‍‭‪‬‍‮()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Frosty.ModSupport.FrostyModExecutor.'g{iqT;PR5)>:JK(mxeNr/JD.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by toonicoopete** [comment]
Dont worry guys I have already solved it

**Comment by supadepo** [comment]
how d you solve it...i have the same problem
