### ISSUE TITLE
Feature request - Exporting models also exports the model's textures

### ISSUE THREAD

**Issue by Flandyn** [GalaxyEham/FrostyToolSuite#80]
Would it be possible to include an option when exporting models that also exports the model's textures?

When exporting a lot of models, it would be much easier and would save a lot of time to include the textures.

EDIT: Is it also possible to export "tinted" textures (for games like MEA, DAI)?

**Comment by GalaxyEham** [comment]
Not possible at this time, and probably not for quite some time.
