### ISSUE TITLE
Значение не может быть неопределенным. Имя параметра: value (Fifa 18)

### ISSUE THREAD

**Issue by Solik91** [GalaxyEham/FrostyToolSuite#83]
Значение не может быть неопределенным.
Имя параметра: value

   в System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
   в FrostySdk.FileSystem.⁪‌⁭‌‫‫‏⁮‮⁭‎‫⁬‪⁭⁭⁭⁫‮⁬⁫‌‍‏‍‮⁯‫‎‮‬⁫‪‪‮‫‮⁮‪‬‮(Byte[] )
   в FrostySdk.FileSystem.Initialize(Byte[] key)
   в FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
English only
