### ISSUE TITLE
Impossible to launch Fifa18 via Frosty Editor or ModManager (with error code)

### ISSUE THREAD

**Issue by flo0263** [GalaxyEham/FrostyToolSuite#86]
Hi guys !
I have a problem, I can not start FIFA18 from Frosty Editor.
Everything worked well before.
When I press on button "launch" Frosty Editor seems to want to start the game but can not. A window appear briefly named : "Origin Games\FIFA 18\FIFASetup\fifaconfig.exe" 
And nothing happens :/

When I use Frosty Mod Manager this error code appear :

> Value cannot be null. 
> Parameter name : value
> 
>    à System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
>    à FrostySdk.FileSystem.‫‭‌‭‫‬⁪‏‭‎⁮⁯‪‎‎‫⁪‏‫⁭⁭‍‍⁯‍⁬‫‫‌‬⁪‍‏⁮⁫​‏⁮‌⁫‮(Byte[] )
>    à FrostySdk.FileSystem.Initialize(Byte[] key)
>    à FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 

I've already tried to remove folder ModData & replace bcrypt file without results.
Visibly the problem could come from Windows 10.

Please I need a solution

Thanks in advance !
Regards flo0263

**Comment by GalaxyEham** [comment]
Duplicate
