### ISSUE TITLE
Can't start Frosty Editor after rebuilding computer

### ISSUE THREAD

**Issue by Charamei** [GalaxyEham/FrostyToolSuite#90]
I recently had to rebuild my computer after a hardware failure, just tried to get Frosty Editor working again, and it's throwing an error when I try to point it to my Inquisition executable:

> Method not found: '!!0[] System.Array.Empty()'.
> 
>    at FrostySdk.Managers.AssetManager.????????????????????????????????????????()
>    at FrostySdk.Managers.AssetManager.Initialize(Boolean additionalStartup)
>    at FrostyEditor.Windows.SplashWindow.<>c__DisplayClass4_0.<LoadData>b__0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at FrostyEditor.Windows.SplashWindow.<LoadData>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at FrostyEditor.Windows.SplashWindow.<Window_Loaded>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

This happens regardless of which version I use, the one I just downloaded or the one I had stored from before the crash. The game is in exactly the same directory it was before, and this is a new hard drive/new Windows 7 install, so there shouldn't be any registry errors causing problems. Help?

ETA: Also, DAI Mod Maker was able to find the game fine, but is currently having issues with recognising that the DDS utilities are installed, which is why I was trying Frosty instead.

**Comment by GalaxyEham** [comment]
Need to upgrade .NET Framework to 4.6 or higher
