### ISSUE TITLE
Frosty Mod Manager Loads without mods but not with mods Mass Effect Andromeda

### ISSUE THREAD

**Issue by frankdoughnuts** [GalaxyEham/FrostyToolSuite#98]
FMM v1.0.4  All permissions are full. Ownership is established on both the game and FMM. I've deleted the mods folder and the bcrypt.dll file in MEA, and deleted the bcrypt file in FMM. Restarted, still not working. I've replaced the bcrypt.dll in FMM with older bcrypt.dll versions, and still no luck. When I click play in FMM with mods loaded, the FMM window immediately mimimizes but nothing happens. Origin says I'm in the MEA game, and my task manager shows a mass effect andromeda process that utilizes exactly 0 of everything. I wait around and nothing happens. I launch the game just fine without mods. I've even tried launching the game with a single mod loaded (I've used multiple single mods in case one of them by itself breaks something) to no avail. Is there anything else I can try?
Best

**Comment by badkarma12** [comment]
Same for me. I think either origin or windows broke it.

**Comment by Kambyo** [comment]
I don't have any mod and FrostyModManager_v1.0.3.1 can launch my fifa 18 but FrostyModManager_v1.0.4.2 can't. Neither of them can launch the game with mods and it shows no error. Help please?
