### ISSUE TITLE
Fifa 18 Crash nach start (modmanager)

### ISSUE THREAD

**Issue by Rednaldo** [GalaxyEham/FrostyToolSuite#99]
**Der Fifa 18 startet kurz und crasht sofort wieder, was kann man da tun?**

**Crashlog:** Ein Teil des Pfades "C:\Program Files (x86)\Fifa 18\FIFA 18\\moddata\patch\win32/superbundlelayout/fifa_installpackage_00/de/cas.cat" konnte nicht gefunden werden.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei System.IO.FileInfo.CopyTo(String destFileName)
   bei Frosty.ModSupport.FrostyModExecutor.?????????????????????????????????????????.?????????????????????????????????????????()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Frosty.ModSupport.FrostyModExecutor.lPlMd\*@hVbE\,4\&u54p7My6\]\[!.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FrostyEditor.MainWindow.<launchButton_Click>d__13.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Ich weiß nicht mehr was ich tun kann.**

**Comment by GalaxyEham** [comment]
1. Make sure to check Run as Administrator for both Frosty and FIFA's exe. Then delete the ModData folder in your FIFA Game Files.
 2. Try moving your Frosty folder to a different drive.
 3. Take ownership of both your FIFA Game Directory and the Frosty Mod Manager folder.
 4. If on Windows 10, add an exception to Windows Defender or any form of antivirus for Frosty.
 5. Use the Frosty 1.0.3alpha4 bcrypt.dll and replace the existing bcrypt.dll in your Frosty Third Party folder https://github.com/GalaxyEham/FrostyToolSuite/releases/tag/v1.0.3alpha
 6. Restart Origin and your PC.

Keep in mind that these fixes are not guaranteed to work. Every setup is different, so you might just have to mess around.

NOTE: Always make sure to delete the ModData folder in your FIFA Game Files every time you try something different.
